# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PyPackets.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PyPackets.proto',
  package='PyPacket',
  serialized_pb=_b('\n\x0fPyPackets.proto\x12\x08PyPacket\"C\n\tdummy_msg\x12\x11\n\tpacketNum\x18\x01 \x02(\r\x12\n\n\x02ID\x18\x02 \x02(\t\x12\x0c\n\x04time\x18\x03 \x02(\x01\x12\t\n\x01s\x18\x04 \x02(\t\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\"c\n\x04Node\x12\n\n\x02ID\x18\x01 \x02(\t\x12\x10\n\x08\x64\x61taType\x18\x02 \x02(\t\x12\x10\n\x08\x63ommType\x18\x03 \x02(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x02(\t\x12\x0c\n\x04port\x18\x05 \x02(\t\x12\x0c\n\x04NMID\x18\x06 \x01(\t\"I\n\nSubscriber\x12\n\n\x02id\x18\x01 \x02(\t\x12\x10\n\x08\x64\x61tatype\x18\x02 \x02(\t\x12\x0c\n\x04port\x18\x03 \x02(\r\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x02(\t\"Y\n\x0bNMHeartBeat\x12\x11\n\tpacketNum\x18\x01 \x02(\r\x12\n\n\x02ID\x18\x02 \x02(\t\x12\x0c\n\x04time\x18\x03 \x02(\x01\x12\x1d\n\x05nodes\x18\x04 \x03(\x0b\x32\x0e.PyPacket.Node\"_\n\rNodeHeartBeat\x12\x11\n\tpacketNum\x18\x01 \x02(\r\x12\n\n\x02ID\x18\x02 \x02(\t\x12\x0c\n\x04time\x18\x03 \x02(\x01\x12!\n\x03sub\x18\x04 \x03(\x0b\x32\x14.PyPacket.Subscriber\"\xe6\x01\n\x0bSixDofState\x12\x11\n\tpacketNum\x18\x01 \x02(\r\x12\n\n\x02ID\x18\x02 \x02(\t\x12\x0c\n\x04time\x18\x03 \x02(\x01\x12\x1e\n\x03NED\x18\x04 \x02(\x0b\x32\x11.PyPacket.Vector3\x12#\n\x08VEL_Iner\x18\x05 \x02(\x0b\x32\x11.PyPacket.Vector3\x12#\n\x08\x41TTITUDE\x18\x06 \x02(\x0b\x32\x11.PyPacket.Vector3\x12 \n\x05OMEGA\x18\x07 \x02(\x0b\x32\x11.PyPacket.Vector3\x12\x1e\n\x03LLA\x18\x08 \x01(\x0b\x32\x11.PyPacket.Vector3\"F\n\x17Simple1AKinematicsState\x12\x11\n\tpacketNum\x18\x01 \x02(\r\x12\n\n\x02ID\x18\x02 \x02(\t\x12\x0c\n\x04time\x18\x03 \x02(\x01\"@\n\x11SimpleDubinsState\x12\x11\n\tpacketNum\x18\x01 \x02(\r\x12\n\n\x02ID\x18\x02 \x02(\t\x12\x0c\n\x04time\x18\x03 \x02(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DUMMY_MSG = _descriptor.Descriptor(
  name='dummy_msg',
  full_name='PyPacket.dummy_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packetNum', full_name='PyPacket.dummy_msg.packetNum', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ID', full_name='PyPacket.dummy_msg.ID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='PyPacket.dummy_msg.time', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='s', full_name='PyPacket.dummy_msg.s', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=96,
)


_VECTOR3 = _descriptor.Descriptor(
  name='Vector3',
  full_name='PyPacket.Vector3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PyPacket.Vector3.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='PyPacket.Vector3.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='PyPacket.Vector3.z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=140,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='PyPacket.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='PyPacket.Node.ID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataType', full_name='PyPacket.Node.dataType', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commType', full_name='PyPacket.Node.commType', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='PyPacket.Node.address', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='PyPacket.Node.port', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NMID', full_name='PyPacket.Node.NMID', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=241,
)


_SUBSCRIBER = _descriptor.Descriptor(
  name='Subscriber',
  full_name='PyPacket.Subscriber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PyPacket.Subscriber.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datatype', full_name='PyPacket.Subscriber.datatype', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='PyPacket.Subscriber.port', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='PyPacket.Subscriber.address', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=316,
)


_NMHEARTBEAT = _descriptor.Descriptor(
  name='NMHeartBeat',
  full_name='PyPacket.NMHeartBeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packetNum', full_name='PyPacket.NMHeartBeat.packetNum', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ID', full_name='PyPacket.NMHeartBeat.ID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='PyPacket.NMHeartBeat.time', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='PyPacket.NMHeartBeat.nodes', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=407,
)


_NODEHEARTBEAT = _descriptor.Descriptor(
  name='NodeHeartBeat',
  full_name='PyPacket.NodeHeartBeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packetNum', full_name='PyPacket.NodeHeartBeat.packetNum', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ID', full_name='PyPacket.NodeHeartBeat.ID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='PyPacket.NodeHeartBeat.time', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub', full_name='PyPacket.NodeHeartBeat.sub', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=504,
)


_SIXDOFSTATE = _descriptor.Descriptor(
  name='SixDofState',
  full_name='PyPacket.SixDofState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packetNum', full_name='PyPacket.SixDofState.packetNum', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ID', full_name='PyPacket.SixDofState.ID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='PyPacket.SixDofState.time', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NED', full_name='PyPacket.SixDofState.NED', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='VEL_Iner', full_name='PyPacket.SixDofState.VEL_Iner', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ATTITUDE', full_name='PyPacket.SixDofState.ATTITUDE', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='OMEGA', full_name='PyPacket.SixDofState.OMEGA', index=6,
      number=7, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LLA', full_name='PyPacket.SixDofState.LLA', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=507,
  serialized_end=737,
)


_SIMPLE1AKINEMATICSSTATE = _descriptor.Descriptor(
  name='Simple1AKinematicsState',
  full_name='PyPacket.Simple1AKinematicsState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packetNum', full_name='PyPacket.Simple1AKinematicsState.packetNum', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ID', full_name='PyPacket.Simple1AKinematicsState.ID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='PyPacket.Simple1AKinematicsState.time', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=739,
  serialized_end=809,
)


_SIMPLEDUBINSSTATE = _descriptor.Descriptor(
  name='SimpleDubinsState',
  full_name='PyPacket.SimpleDubinsState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packetNum', full_name='PyPacket.SimpleDubinsState.packetNum', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ID', full_name='PyPacket.SimpleDubinsState.ID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='PyPacket.SimpleDubinsState.time', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=811,
  serialized_end=875,
)

_NMHEARTBEAT.fields_by_name['nodes'].message_type = _NODE
_NODEHEARTBEAT.fields_by_name['sub'].message_type = _SUBSCRIBER
_SIXDOFSTATE.fields_by_name['NED'].message_type = _VECTOR3
_SIXDOFSTATE.fields_by_name['VEL_Iner'].message_type = _VECTOR3
_SIXDOFSTATE.fields_by_name['ATTITUDE'].message_type = _VECTOR3
_SIXDOFSTATE.fields_by_name['OMEGA'].message_type = _VECTOR3
_SIXDOFSTATE.fields_by_name['LLA'].message_type = _VECTOR3
DESCRIPTOR.message_types_by_name['dummy_msg'] = _DUMMY_MSG
DESCRIPTOR.message_types_by_name['Vector3'] = _VECTOR3
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Subscriber'] = _SUBSCRIBER
DESCRIPTOR.message_types_by_name['NMHeartBeat'] = _NMHEARTBEAT
DESCRIPTOR.message_types_by_name['NodeHeartBeat'] = _NODEHEARTBEAT
DESCRIPTOR.message_types_by_name['SixDofState'] = _SIXDOFSTATE
DESCRIPTOR.message_types_by_name['Simple1AKinematicsState'] = _SIMPLE1AKINEMATICSSTATE
DESCRIPTOR.message_types_by_name['SimpleDubinsState'] = _SIMPLEDUBINSSTATE

dummy_msg = _reflection.GeneratedProtocolMessageType('dummy_msg', (_message.Message,), dict(
  DESCRIPTOR = _DUMMY_MSG,
  __module__ = 'PyPackets_pb2'
  # @@protoc_insertion_point(class_scope:PyPacket.dummy_msg)
  ))
_sym_db.RegisterMessage(dummy_msg)

Vector3 = _reflection.GeneratedProtocolMessageType('Vector3', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3,
  __module__ = 'PyPackets_pb2'
  # @@protoc_insertion_point(class_scope:PyPacket.Vector3)
  ))
_sym_db.RegisterMessage(Vector3)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
  DESCRIPTOR = _NODE,
  __module__ = 'PyPackets_pb2'
  # @@protoc_insertion_point(class_scope:PyPacket.Node)
  ))
_sym_db.RegisterMessage(Node)

Subscriber = _reflection.GeneratedProtocolMessageType('Subscriber', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBER,
  __module__ = 'PyPackets_pb2'
  # @@protoc_insertion_point(class_scope:PyPacket.Subscriber)
  ))
_sym_db.RegisterMessage(Subscriber)

NMHeartBeat = _reflection.GeneratedProtocolMessageType('NMHeartBeat', (_message.Message,), dict(
  DESCRIPTOR = _NMHEARTBEAT,
  __module__ = 'PyPackets_pb2'
  # @@protoc_insertion_point(class_scope:PyPacket.NMHeartBeat)
  ))
_sym_db.RegisterMessage(NMHeartBeat)

NodeHeartBeat = _reflection.GeneratedProtocolMessageType('NodeHeartBeat', (_message.Message,), dict(
  DESCRIPTOR = _NODEHEARTBEAT,
  __module__ = 'PyPackets_pb2'
  # @@protoc_insertion_point(class_scope:PyPacket.NodeHeartBeat)
  ))
_sym_db.RegisterMessage(NodeHeartBeat)

SixDofState = _reflection.GeneratedProtocolMessageType('SixDofState', (_message.Message,), dict(
  DESCRIPTOR = _SIXDOFSTATE,
  __module__ = 'PyPackets_pb2'
  # @@protoc_insertion_point(class_scope:PyPacket.SixDofState)
  ))
_sym_db.RegisterMessage(SixDofState)

Simple1AKinematicsState = _reflection.GeneratedProtocolMessageType('Simple1AKinematicsState', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLE1AKINEMATICSSTATE,
  __module__ = 'PyPackets_pb2'
  # @@protoc_insertion_point(class_scope:PyPacket.Simple1AKinematicsState)
  ))
_sym_db.RegisterMessage(Simple1AKinematicsState)

SimpleDubinsState = _reflection.GeneratedProtocolMessageType('SimpleDubinsState', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEDUBINSSTATE,
  __module__ = 'PyPackets_pb2'
  # @@protoc_insertion_point(class_scope:PyPacket.SimpleDubinsState)
  ))
_sym_db.RegisterMessage(SimpleDubinsState)


# @@protoc_insertion_point(module_scope)
